pytest:
  image: $DOCKER_BASE_IMAGE
  tags:
    - t4
  before_script:
    - "[ -f $HOME/.config/pip/pip.conf ] && rm $HOME/.config/pip/pip.conf"
    - "[ -f $HOME/.pip/pip.conf ] && rm $HOME/.pip/pip.conf"
    - "[ -f $HOME/.wgetrc ] && rm $HOME/.wgetrc"
    - "[ -f $HOME/.curlrc ] && rm $HOME/.curlrc"
    - apt update -y
    - apt install zip -y
    - pip config set global.index-url $PYPI_INDEX
    - pip install -U pip setuptools wheel
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip install -e .
    - sh download_checkpoints.sh
  script:
    - pytest -v --cov .

variables:
  PYPI_INDEX: "https://pypi.tuna.tsinghua.edu.cn/simple"
  DOCKER_BASE_IMAGE: "registry.dp.tech/dptech/prod-11542/clean-container:ubuntu2204-py310-cuda121"
