pytest:
  image: $DOCKER_BASE_IMAGE
  tags:
    - t4
  before_script:
    - "[ -f $HOME/.config/pip/pip.conf ] && rm $HOME/.config/pip/pip.conf"
    - "[ -f $HOME/.pip/pip.conf ] && rm $HOME/.pip/pip.conf"
    - "[ -f $HOME/.wgetrc ] && rm $HOME/.wgetrc"
    - "[ -f $HOME/.curlrc ] && rm $HOME/.curlrc"
    - apt update -y
    - apt install zip -y
    - pip config set global.index-url $PYPI_INDEX
    - pip install -U pip
    - pip install setuptools_scm pytest pytest-cov
    - sh download_checkpoints.sh
    - pip install -e .
    - pytest .
  script:
    - pytest -v --cov test/

variables:
  PYPI_INDEX: "https://pypi.tuna.tsinghua.edu.cn/simple"
  DOCKER_BASE_IMAGE: "registry.dp.tech/dptech/prod-11542/clean-container:ubuntu2204-py310-cuda121"