pytest:
  image: $DOCKER_BASE_IMAGE
  tags:
    - t4
  before_script:
    - "[ -f $HOME/.config/pip/pip.conf ] && rm $HOME/.config/pip/pip.conf"
    - "[ -f $HOME/.pip/pip.conf ] && rm $HOME/.pip/pip.conf"
    - "[ -f $HOME/.wgetrc ] && rm $HOME/.wgetrc"
    - "[ -f $HOME/.curlrc ] && rm $HOME/.curlrc"
    - apt update -y
    - apt install zip -y
    - pip config set global.index-url $PYPI_INDEX
    - pip install -U pip setuptools wheel
    # Setup SSH keys for Project A and Project B
    - mkdir -p ~/.ssh
    - echo "$DPROTEIN_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa_dpt
    - chmod 600 ~/.ssh/id_rsa_dpt
    - echo "$RNA_TF_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa_rna_tf
    - chmod 600 ~/.ssh/id_rsa_rna_tf
    # Create SSH config file to use different keys for different repos
    - |
      echo "
      Host deepprotein
        HostName git.dp.tech
        User git
        IdentityFile ~/.ssh/id_rsa_dpt

      Host unirna_transformers
        HostName git.dp.tech
        User git
        IdentityFile ~/.ssh/id_rsa_rna_tf
      " > ~/.ssh/config
    - GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_dpt' pip install git+ssh://deepprotein/macromolecule/deepprotein@deeprna
    - GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_rna_tf' pip install git+ssh://unirna_transformers/macromolecule/unirna_transformers@main
    - pip install -e .
    - sh download_checkpoints.sh
  script:
    - pytest -v --cov .

variables:
  PYPI_INDEX: "https://pypi.tuna.tsinghua.edu.cn/simple"
  DOCKER_BASE_IMAGE: "registry.dp.tech/dptech/prod-11542/clean-container:ubuntu2204-py310-cuda121"
